services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apbd_lecture9_db_first
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "14333:1433"
